/* RENAMING like >>>>>>>>>>>>
>>>[ export const GET_SERIES = "GET_SERIES"; ]*/
export const LOADING_TRUE = "LOADING_TRUE";
export const LOADING_FALSE = "LOADING_FALSE";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATEGORY = "GET_CATEGORY";
export const SELECT_CHANGE_VAL = "SELECT_CHANGE_VAL";
export const SEARCH_VAL = "SEARCH_VAL";
export const SHOW_SEARCH_RESULT = "SHOW_SEARCH_RESULT";
export const SHOW_SELECT_CHANGE_VAL = "SHOW_SELECT_CHANGE_VAL";
export const SELECTED_IMAGE = "SELECTED_IMAGE";
export const SINGLE_CONTENT = "SINGLE_CONTENT";
// export const GET_IMG_SCALED = "GET_IMG_SCALED";